### ISSUE TITLE
 Is Python version of >=3.8 really needed for compatibility?

### ISSUE THREAD

**Issue by slook** [Nachtalb/nicotine_plus_plugin_template#1]
I wonder if this excellent work for the N+ plugin system actually uses any functions that are only available in Python 3.8, or if it would be possible to broaden the compatibility to bring it in line with the Nicotine+ core?

See recent Nicotine+ commit: https://github.com/nicotine-plus/nicotine-plus/commit/fb96e79ceb13dce476029398b88849c67fa76549

In https://github.com/nicotine-plus/nicotine-plus/issues/1488 the implemented solution re-enabled support for running Nicotine+ 3.2.0 natively on Debian 9 Stretch LTS systems, which is an OS is supported until June 2022 (see https://www.debian.org/releases/stretch/).

My query is in reference to: https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DEVELOPING.md#dependencies ...
_"We aim to support the oldest minor Python 3 version still used by supported releases of distributions and operating systems. The minimum version Nicotine+ currently supports is 3.5."_
...
_"Nicotine+ aims to be as portable as possible, providing access to the Soulseek network for people who cannot run the official Soulseek client. Nicotine+ runs on almost any architecture and system available, and has active users on a plethora of different systems."_

Hopefully you will find this information useful. Thank you for your time.

Context: https://github.com/Nachtalb/nicotine_plus_plugin_template/blob/master/README.md#compatibility

**Comment by Nachtalb** [comment]
> needed?

no 

> will I make my plugins compatible with 3.5?

also no

What I can do is maybe make the core 3.6+ and some of them or 3.7+ compatible. If it happens to be compatible with earlier versions - luck. 3.5 has been EOL for over a year and in 3 months or so 3.6 will be EOL. I personally do not care about EOL versions even if some distros still want to support it for some reason. 

I don't condemn people for using outdated versions but I still implore you to upgrade.

**Comment by slook** [comment]
> What I can do is maybe make the core 3.6+ and some of them or 3.7+ compatible.

That's very fair @Nachtalb , I agree some distros have been needlessly slow at keeping the Python runtime current.

BTW the detailed documentation that goes with your template is fantastic.
